import { OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { DevicesService } from '../devices/devices.service';
import { TrackingService } from '../tracking/tracking.service';
import { TrackingGateway } from '../tracking/tracking.gateway';
import { VideoRecordingsService } from '../video-recordings/video-recordings.service';
export declare class TcpServerService implements OnModuleInit, OnModuleDestroy {
    private devicesService;
    private trackingService;
    private trackingGateway;
    private videoRecordingsService;
    private readonly logger;
    private server;
    private sessions;
    private heartbeatInterval;
    private readonly mediaDir;
    constructor(devicesService: DevicesService, trackingService: TrackingService, trackingGateway: TrackingGateway, videoRecordingsService: VideoRecordingsService);
    onModuleInit(): void;
    onModuleDestroy(): void;
    private startServer;
    private handleConnection;
    private processBuffer;
    private handleMessage;
    private handleRegistration;
    private handleAuthentication;
    private handleHeartbeat;
    private handleDeregistration;
    private handleLocationReport;
    private hasActiveAlarm;
    private triggerAlarmCapture;
    private handleBulkLocation;
    private handleTerminalProperties;
    private handleTerminalParamsResponse;
    private handleVehicleControlResponse;
    private handleMultimediaEvent;
    private handleMultimediaData;
    private handleDriverIdentity;
    private startHeartbeatMonitor;
    getConnectedDevices(): {
        phone: string;
        authenticated: boolean;
        lastHeartbeat: Date;
    }[];
    sendCommand(imei: string, messageId: number, body: Buffer): boolean;
    private getSession;
    sendVehicleControl(imei: string, controlFlags: number): boolean;
    sendQueryLocation(imei: string): boolean;
    sendTempTracking(imei: string, interval: number, validity: number): boolean;
    sendSetParams(imei: string, params: {
        id: number;
        value: Buffer;
    }[]): boolean;
    sendQueryParams(imei: string, paramIds?: number[]): boolean;
    sendTextMessage(imei: string, flags: number, text: string): boolean;
    sendTerminalControl(imei: string, cmd: number, param?: string): boolean;
    sendCameraShoot(imei: string, channel: number, command: number, interval?: number, savingFlag?: number, resolution?: number, quality?: number, brightness?: number, contrast?: number, saturation?: number, chroma?: number): boolean;
    sendRealtimeVideoRequest(imei: string, serverIp: string, serverTcpPort: number, serverUdpPort: number, channel: number, dataType?: number, streamType?: number): boolean;
    sendVideoControl(imei: string, channel: number, command: number, closeType?: number): boolean;
    sendHistVideoRequest(imei: string, channel: number, mediaType: number, streamType: number, storageType: number, playbackMode: number, playbackSpeed: number, startTime: Date, endTime: Date, serverIp: string, serverTcpPort: number, serverUdpPort: number): boolean;
    sendFileListQuery(imei: string, channel: number, startTime: Date, endTime: Date, alarmFlag?: number, mediaType?: number, storageType?: number): boolean;
    sendFileUploadControl(imei: string, serverIp: string, serverTcpPort: number, channel: number, startTime: Date, endTime: Date, alarmFlag: number, mediaType: number, storageType: number, taskId: number, condition: number): boolean;
    sendPtzControl(imei: string, channel: number, speed: number, cmd: number): boolean;
}
